pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
      delete_head_branch:
        force: true
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot-preview[bot]
    actions:
      merge:
        method: merge
      delete_head_branch:
        force: true
 
