version: 2.1
defaults: &defaults
  working_directory: ~/agile-brazil-hotsite
  docker:
    - image: node:lts
jobs:
  staging:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Add SSH Server host key to known_hosts and rsync
          command: |
            apt update && apt install rsync -y && \
            ssh-keyscan -t rsa $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy to staging
          command: |
            cd website && \
            make deploy-to-staging
  production:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Add SSH Server host key to known_hosts and rsync
          command: |
            apt update && apt install rsync -y && \
            ssh-keyscan -t rsa $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy to production
          environment:
            NODE_ENV: production
          command: |
            cd website && \
            make deploy-to-production
workflows:
  version: 2
  deploy:
    jobs:
      - staging:
          filters:
            branches:
              only:
                - "2020"
      - production:
          filters:
            branches:
              only:
                - master